### ISSUE TITLE
"Failed to update mini-batch" error

### ISSUE THREAD

**Issue by Toukiletoukan** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#17] opened 2018-08-02 09:55 UTC
Hello,

Can you help me with this kind of error ?

Microsoft.Azure.Documents.DocumentClientException: Partition range id 37 | Failed to update mini-batch. Exception was Message: {"Errors":["Encountered exception while executing function. Exception = ReferenceError: Variable undefined in strict mode\r\nStack trace: ReferenceError: Variable undefined in strict mode\n at handleUpdate (__.sys.commonBulkInsert.js:5008:17)\n at processOneResult (__.sys.commonBulkInsert.js:4982:29)\n at queryCallback (__.sys.commonBulkInsert.js:4960:21)\n at Anonymous function (__.sys.commonBulkInsert.js:608:29)"]} ActivityId: 8c9fc08f-5747-4fea-a2f0-902407d2be49, Request URI: /apps/950b32f2-6902-4b2e-9311-eca73a7e886f/services/09752978-721d-4448-bc1d-c581088b0cc4/partitions/f77bdba0-f142-4253-9f49-067f91e211d7/replicas/131756540677034031p/, RequestStats: , SDK: Microsoft.Azure.Documents.Common/2.0.0.0, documentdb-dotnet-sdk/2.0.0 Host/64-bit MicrosoftWindowsNT/6.2.9200.0. Status code was 400, documentdb-dotnet-sdk/2.0.0 Host/64-bit MicrosoftWindowsNT/6.2.9200.0 ---> Microsoft.Azure.Documents.DocumentClientException: Message: {"Errors":["Encountered exception while executing function. Exception = ReferenceError: Variable undefined in strict mode\r\nStack trace: ReferenceError: Variable undefined in strict mode\n at handleUpdate (__.sys.commonBulkInsert.js:5008:17)\n at processOneResult (__.sys.commonBulkInsert.js:4982:29)\n at queryCallback (__.sys.commonBulkInsert.js:4960:21)\n at Anonymous function (__.sys.commonBulkInsert.js:608:29)"]} ActivityId: 8c9fc08f-5747-4fea-a2f0-902407d2be49, Request URI: /apps/950b32f2-6902-4b2e-9311-eca73a7e886f/services/09752978-721d-4448-bc1d-c581088b0cc4/partitions/f77bdba0-f142-4253-9f49-067f91e211d7/replicas/131756540677034031p/, RequestStats: , SDK: Microsoft.Azure.Documents.Common/2.0.0.0, documentdb-dotnet-sdk/2.0.0 Host/64-bit MicrosoftWindowsNT/6.2.9200.0 

Thanks for your help...

**Comment by Toukiletoukan** [comment] 2018-08-06 15:36
Hi,

Any help on this issue please ?

Thanks

**Comment by HiroyukiSakoh** [comment] 2018-08-07 18:34
I am facing the same problem.
It seems there is information here.
https://github.com/MicrosoftDocs/azure-docs/issues/12623

**Comment by Toukiletoukan** [comment] 2018-08-07 19:38
Thanks @HiroyukiSakoh !

**Comment by HiroyukiSakoh** [comment] 2018-08-09 01:57
It has been moved from Docs to here.
@tknandu
Is there any information on this issue?

**Comment by Toukiletoukan** [comment] 2018-08-14 13:35
Any update @tknandu  ?

**Comment by RanjeetKumar27** [comment] 2018-08-17 17:39
Hi. This a blocking issue for us. We too are waiting for the fix to roll out. We have facing customer escalation because of this issue. Team, please report on the status.

**Comment by HiroyukiSakoh** [comment] 2018-08-17 23:39
I created a new DatabaseAccount in JapanWest region and tried BulkUpdate to work.
BulkUpdate worked fine now.

(I feel the CosmosDB team is not checking this repository.

**Comment by cpwood** [comment] 2018-09-22 14:59
Having all sorts of problems with Azure Data Factory at the moment too with a similar error message:

https://social.msdn.microsoft.com/Forums/en-US/964966e5-9c65-46ef-9b56-44c52e5ee3bb/adf-copy-error?forum=AzureDataFactory&prof=required

Related?

**Comment by pradeepkumargali** [comment] 2018-09-22 18:09
We are facing the issue issue too in ADF.

**Comment by abinav2307** [comment] 2019-02-23 02:32
Hi all,

Sincere apologies for the delay. We rolled out a fix for this in September 2018 and this issue has now been fixed. Please feel free to re-open this issue if anyone is still running into this problem.

We also have a new version of the BulkExecutor which was just released - https://www.nuget.org/packages/Microsoft.Azure.CosmosDB.BulkExecutor/

**Closed by abinav2307** 2019-02-23 02:32 UTC
