### ISSUE TITLE
Thanks. Any sample for bulkExecuter.BulkDeleteAsync

### ISSUE THREAD

**Issue by zaalion** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#37] opened 2019-01-23 22:16 UTC
Hi,

Do you have any sample for bulkExecuter.BulkDeleteAsync?

Thanks,
Reza

**Comment by ogliznutsa** [comment] 2019-01-24 07:44
Duplicate of https://github.com/Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started/issues/30

**Comment by cgelon** [comment] 2019-02-15 19:22
The latest package (1.4.0) has changed the parameters of BulkDeleteAsync to be a List<Tuple<string, string>> of PartitionKey and ID (PartitionKey is first and ID of the document is second) and an optional integer of batch delete size; providing it with a list of tuples should now be pretty straightforward.

**Comment by abinav2307** [comment] 2019-02-20 07:31
We recently noticed a bug in the query overload for BulkDelete, because of which it was removed in the latest version(s). 

Currently, out BulkDelete only supports <Partition key, id> tuples as input. 

However, we are working on a fix for the query overload as well and will add a sample as soon as the fix is released.

**Comment by abinav2307** [comment] 2019-02-21 05:38
Updated the sample for .NET with BulkDelete here - https://github.com/Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started

**Closed by abinav2307** 2019-02-21 05:38 UTC
